# Generated by Django 5.0.2 on 2024-02-15 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='staff_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
