# Generated by Django 5.0.2 on 2024-02-16 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_employment_dependants_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionsOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=200, unique=True)),
            ],
        ),
    ]
