# Generated by Django 5.0.2 on 2024-02-22 06:04

import app.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_regionsoption'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line1', models.CharField(max_length=250, null=True)),
                ('address_line2', models.CharField(max_length=250, null=True)),
                ('town_city', models.CharField(max_length=150, null=True)),
                ('country', models.CharField(max_length=150, null=True)),
                ('post_code', models.CharField(max_length=150, null=True)),
                ('detail_of', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContactInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=150, null=True)),
                ('type_of', models.CharField(max_length=12, null=True)),
                ('mobile', models.CharField(max_length=12, null=True)),
                ('detail_of', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_skills', models.CharField(max_length=150, null=True)),
                ('license_no', models.CharField(max_length=150, null=True)),
                ('planned_date', models.DateField(null=True)),
                ('acquired_date', models.DateField(null=True)),
                ('expires_date', models.DateField(null=True)),
                ('pais', models.CharField(max_length=150, null=True)),
                ('uplod_certificate', models.FileField(null=True, upload_to=app.models.filepath_certificate)),
                ('detail_of', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
